import Head from "next/head";
import { Main } from "../layout/";

export default function Home() {
    return (
        <>
            <Head>
                <title>ALI Dev Book</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Main />
            </main>
        </>
    );
}
